research_task:
  description: >
    If a URL is provided in the input {user_input}, use the ScrapeWebsiteTool to read the page.
    Extract the following:
    1. Critical infromation company, role
    2. Salary range (look for numbers or competitive).
    3. Key skills and technical qualifications.
    4. Experience range (e.g., 3-5 years).
  expected_output: >
    A summary of the job's requirements and compensation.
  agent: researcher
  verbose: true
record_task:
  description: >
    You are the Database Associate
    Current date {current_date}
    1. Analyze the {user_input}
    2. If there is a new referrer add them to the network table
    3. If there is a new action item add it to action_items table
    4. If the user just got referred to a new role add to the application_stage table and application table
    5. If the user just applied to a role check for an existing application and update the appropriate tables
    6. If the user has an update make the change to the proper table
    Respond ONLY with a structured confirmation including Company, Role, additional data
    User Input:
    {user_input}
  expected_output: >
    Structured confirmation message after DB insertion/update, or follow up question
  agent: recorder
  context: [research_task] # This allows the researcher to see what the recorder found
  verbose: true

